import { test } from 'node:test'
import assert from 'node:assert/strict'
import { humanText } from '../core/prompts.ts'

/**
 * Shapes taken from real agent logs, with the words invented. One "request"
 * in six on the machine this was measured on was one of the machine ones.
 */

test('the tool talking is not a request', () => {
  for (const turn of [
    '<task-notification> <task-id>b1e</task-id> <status>completed</status> </task-notification>',
    '<command-name>/model</command-name> <command-message>model</command-message> <command-args></command-args>',
    '<local-command-stdout>Set model to Opus</local-command-stdout>',
    '<recommended_plugins> Here is a list of plugins </recommended_plugins>',
    '<environment_context> <shell>zsh</shell> <current_date>2026-03-12</current_date> </environment_context>',
    '<system-reminder> The user started this session without a folder </system-reminder>',
    '[Request interrupted by user for tool use]',
    'Caveat: The messages below were generated by the user while running local commands.',
  ]) assert.equal(humanText(turn), null, turn)
})

test('the words inside a wrapper are kept', () => {
  assert.equal(humanText('<realtime_delegation> <input>Draw a plane</input> <transcript_delta>user: Draw a plane</transcript_delta> </realtime_delegation>'),
    'Draw a plane', 'what was said to the voice')
  assert.equal(humanText('<image name=[Image #1] path="/tmp/shot.png"> </image> [Image #1] the chart is missing on mobile'),
    'the chart is missing on mobile', 'the text after an attached image')
  assert.equal(humanText('<in-app-browser-context source="ambient-ui-state"> This block shows example.org </in-app-browser-context> ## My request: what do you see'),
    'what do you see', 'the request after the browser\'s context')
})

test('an ordinary request passes untouched', () => {
  assert.equal(humanText('look at SUP-12, the login loops'), 'look at SUP-12, the login loops')
  assert.equal(humanText('  two   spaces\nand a line  '), 'two spaces and a line')
  assert.equal(humanText(''), null)
  assert.equal(humanText(null), null)
})
